interfaces:
      cumulus1:
        int_numbered:
          eth0:
            ip_and_mask: "10.0.100.1/24"
    
          swp1:
            ip_and_mask: "192.168.100.1/24"
        
          swp2:
            ip_and_mask: "172.16.100.1/24"
        
      cumulus2:
        int_numbered:
          eth0:
            ip_and_mask: "10.0.200.1/24"
    
          swp1:
            ip_and_mask: "192.168.200.2/24"
        
          swp2:
            ip_and_mask: "172.16.200.2/24"
        